version: '2'
services:
  api:
    # build: 
    #   context: ./
    #   dockerfile: ./Dockerfile
    restart: always
    image: ccr.ccs.tencentyun.com/ftqq/checkchan:latest
    volumes:
      # - './api:/api'
      - './data:/data'
    ports:
      - '8088:80'
    environment:
      - API_KEY=aPiKe1
      - ERROR_IMAGE=NORMAL # NONE,NORMAL,FULL
      - SNAP_URL_BASE=http://... # NONE,NORMAL,FULL
      - SNAP_FULL=1 # NONE,NORMAL,FULL
      - TZ=Asia/Chongqing